"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import { AppShell } from "@/components/layout/app-shell";
import { PageHeader } from "@/components/layout/page-header";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { EmptyState } from "@/components/ui/empty-state";
import { Spinner } from "@/components/ui/spinner";
import { TrackerSelector } from "@/components/shared/tracker-selector";
import { SentimentBadge } from "@/components/shared/sentiment-badge";
import { topicsApi, trackersApi } from "@/lib/api";
import { useAuth } from "@/components/providers/auth-provider";
import type { TopicCluster, Tracker } from "@/lib/types";
import { RefreshCw } from "lucide-react";

function sentimentLabel(t: TopicCluster): "positive" | "negative" | "neutral" {
  const d = t.dominant_sentiment;
  if (d === "positive" || d === "negative" || d === "neutral") return d;
  return "neutral";
}

export default function TopicsPage() {
  const { user } = useAuth();
  const [trackers, setTrackers] = useState<Tracker[]>([]);
  const [trackerId, setTrackerId] = useState("");
  const [topics, setTopics] = useState<TopicCluster[]>([]);
  const [loading, setLoading] = useState(true);
  const [reclustering, setReclustering] = useState(false);

  useEffect(() => {
    trackersApi.list().then(setTrackers).catch(console.error);
  }, []);

  async function load() {
    setLoading(true);
    topicsApi.list(trackerId ? { tracker_id: trackerId } : {})
      .then(setTopics)
      .catch(console.error)
      .finally(() => setLoading(false));
  }

  useEffect(() => { load(); }, [trackerId]);

  async function handleRecluster() {
    setReclustering(true);
    await topicsApi.recluster(trackerId || undefined);
    setTimeout(() => { load(); setReclustering(false); }, 5000);
  }

  return (
    <AppShell accountName={user?.account_name}>
      <PageHeader
        title="Topics"
        description="BERTopic-style clustering of recent mentions"
        action={
          <div className="flex items-center gap-2">
            <TrackerSelector trackers={trackers} value={trackerId} onChange={setTrackerId} />
            <Button size="sm" variant="default" onClick={handleRecluster} disabled={reclustering}>
              {reclustering ? <Spinner /> : <RefreshCw size={13} />}
              Recluster
            </Button>
          </div>
        }
      />

      <div className="mt-6">
        {loading ? (
          <div className="flex items-center gap-3 py-16 justify-center">
            <Spinner /> <span className="text-sm text-muted-foreground">Loading...</span>
          </div>
        ) : topics.length === 0 ? (
          <div className="border border-border rounded-lg">
            <EmptyState
              title="No topics yet"
              description="Topics are generated by clustering mentions. Click Recluster to start."
              action={
                <Button size="sm" variant="default" onClick={handleRecluster} disabled={reclustering}>
                  <RefreshCw size={13} /> Recluster now
                </Button>
              }
            />
          </div>
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {topics.map((t) => (
              <Link
                key={t.id}
                href={`/topics/${t.id}`}
                className="border border-border rounded-lg p-5 hover:bg-surface transition-colors block"
              >
                <div className="flex items-start justify-between gap-2 mb-3">
                  <p className="font-semibold text-sm leading-tight">{t.label}</p>
                  <SentimentBadge label={sentimentLabel(t)} />
                </div>
                <div className="flex flex-wrap gap-1 mb-3">
                  {t.keywords.slice(0, 6).map((k) => (
                    <Badge key={k} variant="muted">{k}</Badge>
                  ))}
                </div>
                <p className="text-xs text-muted-foreground">
                  {t.mention_count.toLocaleString()} mentions · avg sentiment {t.sentiment_avg.toFixed(2)}
                </p>
              </Link>
            ))}
          </div>
        )}
      </div>
    </AppShell>
  );
}
